version: "3.9"

services:
  db:
    image: ankane/pgvector:latest
    container_name: DB
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: crm
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d


  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/public:/app/public
      - ./backend/generated:/app/generated
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/nest-cli.json:/app/nest-cli.json
    env_file:
      - ./backend/.env.docker
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app       # live reload з локального коду
      - /app/node_modules     # щоб node_modules не перезаписувалися
    environment:
      - CHOKIDAR_USEPOLLING=true  # щоб CRA спостерігав за файлами у Docker
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  pgdata: